version: "3"
services:
  go:
    build:
      context: .
      args:
        - VARIANT=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspace
      - ${HOME}/.ssh:/home/vscode/.ssh
    command: sleep infinity
    environment:
      - GOROOT=/usr/local/go
  db:
    image: postgres:12
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
volumes:
  db_volume:
